services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslodb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data