services:
  api:
    image: josecsanchezfer/teslo-api:0.0.2
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL=false
      - PORT=3000
      - HOST_API=http://localhost:3000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres:
